name: CI
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: make lint
      - run: make benchmark
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install --no-optional --no-audit --no-fund --progress=false
      - run: npm run lint
      - run: make test-coverage
      - run: |
          pip install coveralls==3.0.1
          coveralls || true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test_compat:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.7"
            toxenv: py37-lower_bound_deps,py37-upper_bound_deps
          - python: "3.8"
            toxenv: py38-lower_bound_deps,py38-upper_bound_deps
          - python: "3.9"
            toxenv: py39-lower_bound_deps
          - python: "3.10"
            toxenv: py310-upper_bound_deps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install tox==3.15.0
      - run: sudo apt-get install libxml2-dev libxslt-dev
      - run: tox --parallel
        env:
          TOXENV: ${{ matrix.toxenv }}
